"""Add batch and production cost columns to Product

Revision ID: 39edc938ff43
Revises: 33fafdd83d94
Create Date: 2025-06-22 09:27:31.269869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39edc938ff43'
down_revision = '33fafdd83d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bake_power_w', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bake_time_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('production_time_hr', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('production_time_hr')
        batch_op.drop_column('bake_time_min')
        batch_op.drop_column('bake_power_w')
        batch_op.drop_column('batch_size')

    # ### end Alembic commands ###
